### ISSUE TITLE
pip install and runtime errors

### ISSUE THREAD

**Issue by StephenQuirolgico** [MilaNLProc/contextualized-topic-models#51]
* Contextualized Topic Models version:
* Python version: 3.8.6, pip: 20.2.1
* Operating System: Windows

### Description

pip install results in torch/torchvision dependency errors. After "fixing" dependency errors, I get some errors related to missing names (e.g., ZeroShotTM) when trying to run the code.

### What I Did

```
pip install -U contextualized_topic_models

Collecting contextualized_topic_models
  Using cached contextualized_topic_models-1.8.1-py2.py3-none-any.whl (29 kB)
Collecting wordcloud==1.8.1
  Using cached wordcloud-1.8.1-cp38-cp38-win_amd64.whl (155 kB)
Collecting scipy==1.4.1
  Using cached scipy-1.4.1-cp38-cp38-win_amd64.whl (31.0 MB)
  Using cached numpy-1.19.1-cp38-cp38-win_amd64.whl (13.0 MB)
ERROR: Could not find a version that satisfies the requirement torchvision==0.7.0 (from contextualized_topic_models) (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.5.0)
ERROR: No matching distribution found for torchvision==0.7.0 (from contextualized_topic_models)
```
To fix this, I pip installed the latest torch and torchvision and reran 'pip install -U contextualized_topic_models' which seemed to complete successfully. However, when I run the example code, I get the following errors:
```
No name 'ZeroShotTM' in module 'contextualized_topic_models.models.ctm'
```
When I view the /venv/contextualized_topic_models/models/ctm.py file in my virtual environment, I see that it does not include class `ZeroShotTM `as it does on Github.

I am also getting similar errors as shown below:
```
No name 'TopicModelDataPreparation' in module
Undefined variable 'load_from_text'
Undefined variable 'MmCorpus'
Undefined variable 'LdaModel'
Undefined variable 'doc2bow'
```

**Comment by vinid** [comment]
Hi @StephenQuirolgico,

I am not able to replicate the error on Linux. I also run the installation on Colab (that runs Linux) and did not have problems. 

Are you sure the second run of `pip install -U contextualized_topic_models` run correctly? 

Can you post the ouptut of the following snippet?:

```python 

import contextualized_topic_models

contextualized_topic_models.__version__
```

In the meantime, we will try to run it again on Windows

**Comment by vinid** [comment]
I think we found the problem. So if you install the latest pytorch version (1.7.0), the only version of the package that matches is the 1.4.1 (that does not have the ZeroShotTM model).

I have fixed this in the latest release (1.8.2), you should be able to run `pip install -U contextualized-topic-models` and get the latest version running without problems

**Comment by StephenQuirolgico** [comment]
Hi @vinid , I am still having issues on Windows. I got it running on Ubuntu (with another error). From PyCharm (on Windows), I see the package is currently at 1.4.1 and that 1.8.2 is available. However, when I try to upgrade it, I get 
`ERROR: Could not find a version that satisfies the requirement torchvision>=0.7.0 (from contextualized-topic-models)` error. On Ubuntu, it makes it to 100 epochs then gives the following error:

**Comment by vinid** [comment]
*Windows*

can you try to wipe the `venv` and recreate it from scratch? I have the fear that there is something that is preventing the package to be installed in the correct way.

*Ubuntu*

This is very weird, k by default is initialized at 10, which means that your input size is less than 10. Do you mind sharing with me the code you are using? I can give a look and see if there is something missing

**Comment by StephenQuirolgico** [comment]
Yes, I created a whole new project on another Windows machine just to verify. I'll try manually cloning the repo and replacing the files in `venv`.

For Ubuntu, yes, I just copied/pasted your example code which has input size less than 10. Thanks.

```
contextualized_topic_models.models.ctm import ZeroShotTM

text_for_contextual = [
    "hello, this is unpreprocessed text you can give to the model",
    "have fun with our topic model",
]
text_for_bow = [
    "hello unpreprocessed give model",
    "fun topic model",
]

qt = TopicModelDataPreparation("distiluse-base-multilingual-cased")
training_dataset = qt.create_training_set(text_for_contextual, text_for_bow)
ctm = ZeroShotTM(input_size=len(qt.vocab), bert_input_size=512, n_components=50)
ctm.fit(training_dataset) # run the model
ctm.get_topics()
```
